
/** X-TRADER FRONTEND - final9 (auto-update + ad-refresh optimized) **/
const API_BASE = "http://localhost:5000";
const REFRESH_MIN = 5;               // 5-minute cadence info-only
const POLL_MS = 3000;                // long-poll (ms)
const STREAM_URL = API_BASE + "/api/stream";

// ---- i18n (unchanged texts) ----
const baseEN = {
  signals_title: "Latest signals (live)",
  signals_desc: "AI trading signals, synchronized every 5 minutes, for operations up to ~2 hours, designed for Binance.",
  tbl_pair: "Pair",
  tbl_signal: "Signal",
  tbl_time: "Time (UTC)",
  loading: "Loading…",
  panel_status_title: "AI system status",
  panel_status_offline: "Offline",
  panel_status_desc_online: "AI is running and sending signals",
  info_title: "⚡ Signal info",
  info_body: "Signals are generated by your AI system and update automatically as new data arrives.",
  footer_note: "AI signals, no financial advice."
};

const ALL_LANGS = [
  ["en","🇺🇸 English"],["zh","🇨🇳 中文"],["es","🇪🇸 Español"],["hi","🇮🇳 हिन्दी"],["ar","🇸🇦 العربية"],
  ["fr","🇫🇷 Français"],["bn","🇧🇩 বাংলা"],["pt","🇵🇹 Português"],["ru","🇷🇺 Русский"],["ur","🇵🇰 اردو"],
  ["id","🇮🇩 Bahasa"],["de","🇩🇪 Deutsch"],["ja","🇯🇵 日本語"],["sw","🇰🇪 Kiswahili"],["tr","🇹🇷 Türkçe"],
  ["ko","🇰🇷 한국어"],["it","🇮🇹 Italiano"],["fa","🇮🇷 فارسی"],["ha","🇳🇬 Hausa"],["vi","🇻🇳 Tiếng Việt"],
  ["th","🇹🇭 ไทย"],["pl","🇵🇱 Polski"],["uk","🇺🇦 Українська"],["ro","🇷🇴 Română"],["nl","🇳🇱 Nederlands"],
  ["el","🇬🇷 Ελληνικά"],["cs","🇨🇿 Čeština"],["hu","🇭🇺 Magyar"],["he","🇮🇱 עברית"],["sv","🇸🇪 Svenska"],
  ["ta","🇮🇳 தமிழ்"],["te","🇮🇳 తెలుగు"],["mr","🇮🇳 मराठी"],["gu","🇮🇳 ગુજરાતી"],["pa","🇮🇳 ਪੰਜਾਬੀ"],
  ["yo","🇳🇬 Yorùbá"],["my","🇲🇲 မြန်မာ"],["zu","🇿🇦 isiZulu"],["am","🇪🇹 አማርኛ"],["ms","🇲🇾 Bahasa Melayu"]
];

const BINANCE_PHRASE = {
  en: "designed for Binance.", it: "studiato per Binance.", es: "diseñado para Binance.",
  fr: "conçu pour Binance.", de: "entwickelt für Binance.", pt: "desenvolvido para a Binance.",
  ru: "разработано для Binance.", ar: "مصمم لمنصة Binance.", hi: "Binance के लिए तैयार किया गया.",
  zh: "为 Binance 优化。", id: "dirancang untuk Binance.", tr: "Binance için tasarlanmıştır.",
  ko: "Binance용으로 설계되었습니다.", ja: "Binance 向けに最適化。", sw: "iliyoundwa kwa Binance.",
  fa: "طراحی‌شده برای Binance.", ha: "an tsara shi don Binance.", vi: "được thiết kế cho Binance.",
  th: "ออกแบบมาสำหรับ Binance", pl: "zaprojektowane dla Binance.", uk: "розроблено для Binance.",
  ro: "conceput pentru Binance.", nl: "ontworpen voor Binance.", el: "σχεδιασμένο για το Binance.",
  cs: "navrženo pro Binance.", hu: "a Binance számára készült.", he: "שנועד עבור Binance.",
  sv: "utformat för Binance.", ta: "Binance க்காக வடிவமைக்கப்பட்டது.", te: "Binance కోసం రూపుదిద్దుకుంది.",
  mr: "Binance साठी तयार केलेले.", gu: "Binance માટે બનાવાયું છે.", pa: "ਜੋ Binance ਲਈ ਬਣਾਇਆ ਗਿਆ ਹੈ.",
  yo: "tí a ṣe fún Binance.", my: "Binance အတွက် ဒီဇိုင်းလုပ်ထားသည်။", zu: "eyiklanyelwe i-Binance.",
  am: "ለ Binance የተዘጋጀ ነው።", ms: "direka untuk Binance.", bn: "Binance এর জন্য তৈরি।"
};

const LANGS = {};
ALL_LANGS.forEach(([code]) => {
  LANGS[code] = { ...baseEN };
  const addon = BINANCE_PHRASE[code] || BINANCE_PHRASE.en;
  if (code==="zh"){
    Object.assign(LANGS[code], {
      signals_title:"最新信号（实时）", tbl_pair:"交易对", tbl_signal:"信号", tbl_time:"时间 (UTC)",
      loading:"加载中…", panel_status_title:"AI 系统状态", panel_status_offline:"离线",
      panel_status_desc_online:"AI 正在运行并发送信号", info_title:"⚡ 信号说明",
      info_body:"信号由你的 AI 系统生成，并在有新数据时自动更新。", footer_note:"AI 信号，仅供参考。"
    });
    LANGS[code].signals_desc = "AI 交易信号，每 5 分钟同步一次，适用于最长约 2 小时的交易，" + addon;
  } else if (code==="es"){
    Object.assign(LANGS[code], {
      signals_title:"Últimas señales (en vivo)", tbl_pair:"Par", tbl_signal:"Señal", tbl_time:"Hora (UTC)",
      loading:"Cargando…", panel_status_title:"Estado del sistema IA", panel_status_offline:"Offline",
      panel_status_desc_online:"La IA está activa y enviando señales", info_title:"⚡ Info de señales",
      info_body:"Las señales son generadas por tu sistema de IA y se actualizan automáticamente cuando llega nuevo dato."
    });
    LANGS[code].signals_desc = "Señales de trading con IA, sincronizadas cada 5 minutos, para operaciones de hasta ~2 horas, " + addon;
  } else if (code==="it"){
    Object.assign(LANGS[code], {
      signals_title:"Ultimi segnali (live)", tbl_pair:"Coppia", tbl_signal:"Segnale", tbl_time:"Orario (UTC)",
      loading:"Caricamento…", panel_status_title:"Stato sistema AI", panel_status_offline:"Offline",
      panel_status_desc_online:"Il sistema AI è attivo e sta inviando segnali", info_title:"⚡ Info segnali",
      info_body:"I segnali sono generati dal tuo sistema AI e si aggiornano automaticamente all'arrivo di nuovi dati."
    });
    LANGS[code].signals_desc = "Segnali di trading AI, sincronizzati ogni 5 minuti, per operazioni fino a ~2 ore, " + addon;
  } else {
    LANGS[code].signals_desc = "AI trading signals, synchronized every 5 minutes, for operations up to ~2 hours, " + addon;
  }
});

// ---- Language selector ----
const langSelect = document.getElementById("langSwitcher");
if (langSelect) {
  ALL_LANGS.forEach(([code,label]) => {
    const o = document.createElement("option");
    o.value = code; o.textContent = label;
    if (code === "en") o.selected = true;
    langSelect.appendChild(o);
  });
  const saved = localStorage.getItem("xtrader_lang");
  if (saved && LANGS[saved]) { langSelect.value = saved; applyLang(saved); } else { applyLang("en"); }
  langSelect.addEventListener("change", e => {
    const lang = e.target.value; applyLang(lang); localStorage.setItem("xtrader_lang", lang);
  });
} else { applyLang("en"); }

function applyLang(lang){
  const dict = LANGS[lang] || baseEN;
  document.querySelectorAll("[data-i18n]").forEach(el=>{
    const k = el.dataset.i18n; if (dict[k]) el.textContent = dict[k];
  });
}

// ---- Live signals (SSE with polling fallback) ----
let lastHash = null;
let etag = null;

// quick hash for change detection
function quickHash(obj){
  try { const s = JSON.stringify(obj); let h = 0; for (let i=0;i<s.length;i++){ h = (h*31 + s.charCodeAt(i)) > 0; } return h.toString(16); }
  catch(e){ return null; }
}

async function fetchLatest(){
  const headers = { "Cache-Control": "no-store" };
  if (etag) headers["If-None-Match"] = etag;
  const res = await fetch(API_BASE + "/api/latest", { headers });
  if (res.status === 304) return { changed:false };
  if (!res.ok) throw new Error("HTTP " + res.status);
  etag = res.headers.get("ETag") || etag;
  const data = await res.json();
  const h = quickHash(data);
  if (h !== lastHash) {
    lastHash = h;
    renderSignals(data); renderSignalCards(data);
    setBackendStatus(true);
    onSignalsUpdated(); // <-- trigger ads refresh on data change
    return { changed:true };
  }
  return { changed:false };
}

async function startLongPoll(){
  while (true){
    try { await fetchLatest(); await waitMs(3000); }
    catch(e){ setBackendStatus(false); await waitMs(10000); }
  }
}

function startSSE(){
  try {
    const es = new EventSource(STREAM_URL, { withCredentials:false });
    let opened = false;
    es.onopen = () => { opened = true; setBackendStatus(true); };
    es.onmessage = (ev) => {
      try{
        const data = JSON.parse(ev.data);
        const h = quickHash(data);
        if (h !== lastHash){
          lastHash = h;
          renderSignals(data); renderSignalCards(data);
          onSignalsUpdated(); // <-- trigger ads refresh
        }
      }catch(e){ /* ignore */ }
    };
    es.onerror = () => { es.close(); startLongPoll(); };
  } catch(e){ startLongPoll(); }
}

function waitMs(ms){ return new Promise(r=>setTimeout(r, ms)); }

// ---- Renderers ----
function renderSignals(list){
  const tbody = document.getElementById("signalRows");
  if(!tbody) return;
  tbody.innerHTML = "";
  const lang = getLang();
  if(!list || list.length===0){
    const tr = document.createElement("tr");
    const td = document.createElement("td");
    td.colSpan = 3; td.textContent = LANGS[lang].loading;
    tr.appendChild(td); tbody.appendChild(tr); return;
  }
  list.forEach(item=>{
    const tr = document.createElement("tr");
    const td1 = document.createElement("td");
    const td2 = document.createElement("td");
    const td3 = document.createElement("td");
    td1.textContent = item.pair || "-";
    const s = (item.signal||"").toUpperCase();
    td2.textContent = s;
    if (s==="BUY") td2.classList.add("signal-buy");
    else if (s==="SELL") td2.classList.add("signal-sell");
    else td2.classList.add("signal-hold");
    const ts = item.timestamp ? new Date(item.timestamp).toISOString().slice(0,19).replace("T"," ") : "-";
    td3.textContent = ts + " UTC";
    tr.appendChild(td1); tr.appendChild(td2); tr.appendChild(td3);
    tbody.appendChild(tr);
  });
}

function renderSignalCards(list){
  const wrap = document.getElementById("signalCards");
  if(!wrap) return; wrap.innerHTML = "";
  const lang = getLang();
  if(!list || list.length===0){
    const div = document.createElement("div");
    div.className = "signal-card";
    div.innerHTML = `
      <div class="pair">-</div>
      <div class="signal signal-hold">-</div>
      <div class="time">${LANGS[lang].loading}</div>
    `;
    wrap.appendChild(div); return;
  }
  list.slice(0,12).forEach(item=>{
    const s = (item.signal||"").toUpperCase();
    const card = document.createElement("div");
    card.className = "signal-card";
    const cls = s==="BUY" ? "signal-buy" : (s==="SELL" ? "signal-sell" : "signal-hold");
    const ts = item.timestamp ? new Date(item.timestamp).toISOString().slice(0,19).replace("T"," ") + " UTC" : "-";
    card.innerHTML = `
      <div class="pair">${item.pair || "-"}</div>
      <div class="signal ${cls}">${s || "-"}</div>
      <div class="time">${ts}</div>
    `;
    wrap.appendChild(card);
  });
}

function setBackendStatus(ok){
  const el = document.getElementById("backendStatus");
  const sub = document.getElementById("backendStatusSub");
  if(!el) return;
  const dict = LANGS[getLang()] || baseEN;
  if(ok){
    el.textContent = "Online";
    el.classList.remove("offline"); el.classList.add("online");
    if (sub) { sub.textContent = dict.panel_status_desc_online; sub.style.display = "inline"; }
  } else {
    el.textContent = dict.panel_status_offline;
    el.classList.remove("online"); el.classList.add("offline");
    if (sub) { sub.style.display = "none"; }
  }
}

function getLang(){ return (document.getElementById("langSwitcher") || {}).value || "en"; }

// ---- AD REFRESH (optimized, non-invasive, policy-friendly) ----
const MIN_SLOT_REFRESH_MS = 60000;   // >= 60s per slot
const PRE_WINDOW_MIN = 30000;        // 30s before next 5m tick
const PRE_WINDOW_MAX = 60000;        // up to 60s before

const adSlots = [
  { id: "ad-slot-1", last: 0 },
  { id: "ad-slot-2", last: 0 },
  { id: "ad-slot-3", last: 0 },
];

// Observe visibility (>=50% in view)
const visMap = {};
const io = new IntersectionObserver(entries=>{
  entries.forEach(e=>{ visMap[e.target.id] = e.isIntersecting; });
}, { threshold: 0.5 });
adSlots.forEach(s=>{
  const el = document.getElementById(s.id);
  if (el) io.observe(el);
});

function refreshAdSlotsInView(){
  adSlots.forEach(s=>{
    const el = document.getElementById(s.id);
    if (!el) return;
    const now = Date.now();
    if (now - s.last < MIN_SLOT_REFRESH_MS) return;
    if (visMap[s.id]) {
      refreshOneSlot(el);
      s.last = now;
    }
  });
}

// Generic refresh: supports image fallback and simple Coinzilla reinjection
function refreshOneSlot(el){
  const type = el.getAttribute("data-ad-type") || "image";
  if (type === "image"){
    const img = el.querySelector("img");
    if (img){
      const base = img.getAttribute("src").split("?")[0];
      img.setAttribute("src", base + "?cb=" + Date.now());
    }
    return;
  }
  if (type === "coinzilla"){
    const zone = el.getAttribute("data-coinzilla-zone");
    if (!zone) return;
    el.innerHTML = ""; // clear
    // Re-inject the tag script for this zone
    const s = document.createElement("script");
    s.src = "https://cdn.coinzilla.io/serve.js";
    s.setAttribute("data-zone", zone);
    el.appendChild(s);
    return;
  }
  // Custom handlers (e.g., GPT) can be attached here:
  if (window.adRefreshHandlers && typeof window.adRefreshHandlers[el.id] === "function"){
    try { window.adRefreshHandlers[el.id](el); } catch(e){}
  }
}

// Dispatch an immediate ad refresh (used on new signals + scheduled)
function dispatchAdRefreshNow(){
  refreshAdSlotsInView();
}

// Triggered when signals change
function onSignalsUpdated(){
  dispatchAdRefreshNow();
}

// Pre-refresh scheduler 30-60s before each 5-min boundary
function scheduleAdPreRefresh(){
  const now = new Date();
  const m = now.getMinutes();
  const next = Math.ceil(m/5)*5;
  const nextDate = new Date(now);
  nextDate.setMinutes(next, 0, 0);
  let diff = nextDate - now;
  if (diff <= 0) diff = 5*60*1000;
  const pre = Math.max(PRE_WINDOW_MIN, Math.min(PRE_WINDOW_MAX, diff - 5000));
  setTimeout(dispatchAdRefreshNow, pre);
  setTimeout(scheduleAdPreRefresh, diff + 1000);
}

// Periodic safety refresh (every 90s) - still in-view and per-slot throttled
setInterval(refreshAdSlotsInView, 90000);

// Kickoff
(async function initLive(){
  try { await fetchLatest(); } catch(e){ /* ignore */ }
  startSSE();
  scheduleAdPreRefresh();
})();
